[workspace]
members = ["client","server","common"]
resolver = "2"

[workspace.dependencies]
rand = "0.8.5"
tonic = "0.12.3"
tonic-build = "0.12.3"
prost = "0.13.3"
tokio = { version = "1.41", features = ["full"] }
